pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./abducensparese.htm","Abducens Palsy","Abducens Palsy In the first example, an abducens palsy of the right eye is simulated. The abducens palsy is an incomitant form of strabismus, i.e....",""],
["./aenderungsbericht.htm","Activity Log","Activity Log The activity log offers the possibility to display a textual list of all changes made between two scenarios from the selected scenari...",""],
["./allgemeinefunktionen.htm","General Functions","General Functions The \"General Functions\" toolbar provides the most important navigation and viewing functions. Use this button to undo changes ma...",""],
["./allgemeines.htm","General","General The general options of SEE++ can be set in a dialog, which can be accessed via the Treeview under \"Options- General\" or via the main menu ...",""],
["./ansichten.htm","Views","Views As already explained in the introduction SEE++ offers four so-called diagram-windows to display different diagrams. In each diagram-window a...",""],
["./avi_filmerstellen.htm","Create Movie","Create Movie Another option to export data from SEE++ is the function to save the current simulation results as an AVI movie for better illustrati...",""],
["./baendermodell.htm","Tape Model","Tape Model Based on the string model, Robinson formulated the so-called tape model in 1975. This model reduces the shift of a muscle&#39;s path on the...",""],
["./bericht.htm","Report","Report The report provides a complete list of all parameters of the currently active simulation model and of their appropriate values. You can acc...",""],
["./bilderspeichern.htm","Save as Image","Save as Image Select \"Save as Image\" from the context menu of a diagram or for the 3D-view from the main menu under \"Patient- 3D-Model- Save as Im...",""],
["./blickschema.htm","Gaze Pattern","Gaze Pattern A gaze pattern forms the basis for the simulation of the Hess-Lancester-Test. When executing the simulation for each point drawn into...",""],
["./blickschema_als_bild_speichern.htm","Save Gaze Pattern as Image","Save Gaze Pattern as Image You can save the nine main gaze directions (default gaze pattern) shown in the 3D-view as a combined image. To do so, s...",""],
["./bulbusdaten.htm","Globe Data","Globe Data The globe data dialog exists for each eye simulated by SEE++ . In this explanation the left eye is used as an example. All specificatio...",""],
["./cover_test.htm","Cover Test","Cover Test The simulation of the cover test is based on the \"Interpolation for Real-Time Assessment\" , so before using the cover test you have to ...",""],
["./cover_test_med_hintergrund.htm","Cover Test","Cover Test The cover test is used for the objective determination of type and extent of eye motility disorders by letting the patient fixate a nea...",""],
["./datenexport.htm","Data Export","Data Export As data export functions the saving of images, videos or the printing of diagrams and views can be summarized in SEE++. These function...",""],
["./diagramme.htm","Diagrams","Diagrams The options for diagrams refer to the visualization of the different views available in SEE++. In this dialog there exists a tab sheet fo...",""],
["./diagrammeallgemein.htm","Diagrams","Diagrams The eight diagrams in SEE++ have certain similarities. One similarity is that per diagram-window only one diagram can be displayed at a t...",""],
["./drucken.htm","Print","Print You can print a diagram via its context menu and the 3D-view via the main menu under \"Patient- 3D-Model- Print\". After selecting the specifi...",""],
["./drucker.htm","Printer","Printer With the \"Printer\" dialog you can specify the settings for the default printer used in SEE++. You can access this dialog via the Treeview ...",""],
["./einfuehrendebeispiele.htm","Examples","Examples This section contains three different examples which were modeled with SEE++: 1. Abducens palsy - as an example of an unilateral muscle p...",""],
["./fadenmodell.htm","String Model","String Model The string model is the simplest representation in order to describe the geometrical effect of eye rotations. It was formulated by Kr...",""],
["./film_fuer_kopfneigetest.htm","Create Movie for Head-Tilt Test","Create Movie for Head-Tilt Test The \"Create Movie for Head-Tilt Test\" function offers the possibility to create AVI movies in a specific gaze posi...",""],
["./geometrischemodelle.htm","Geometrical Models","Geometrical Models SEE++ implements purely geometrical models (string model and tape model) as well as kinematic models with geometrical component...",""],
["./grundlagenderanatomie.htm","Anatomy of the Human Eye","Anatomy of the Human Eye The eyes, the \"sense of visual perception\", rank among the most important sensory organs of the human organism. They prov...",""],
["./hess_diagramm.htm","Hess-Diagram","Hess-Diagram There exist two Hess-diagrams in the SEE++ program: one for the left eye with the right eye fixing and one for the right eye with the...",""],
["./hess_lancastertest.htm","Hess-Lancaster Test","Hess-Lancaster Test The Hess-Lancaster test or Hess test is a test for binocular functions with separated images for both eyes. This clinical test...",""],
["./innervationsverteilung.htm","Distribution of Innervations","Distribution of Innervations The distribution of innervations dialog controls the muscles activation potential based on the stimulations created b...",""],
["./interpolation_fuer_echtzeit_di.htm","Interpolation for Real-Time Assessment","Interpolation for Real-Time Assessment The interpolation for real-time assessment can be accessed via the \"General Functions\" toolbar . After clic...",""],
["./kinematischemodelle.htm","Kinematic Model","Kinematic Model In order to be able to completely simulate a mechanical system, apart from geometrical structures, the simulation of forces is als...",""],
["./klinischereinsatz.htm","Clinical Use","Clinical Use Due to the fact that this system has to be primary considered as research support, important restrictions for the clinical deployment...",""],
["./kraeftemodell.htm","Muscle Force Model","Muscle Force Model The goal of the muscle force model is to simulate the behavior of a muscle as a function of its length and innervation. This is...",""],
["./medizinischestammdaten.htm","Medical Data","Medical Data The medical data contains all necessary information for the modeling and simulation of a \"virtual patient\". Furthermore, some of the ...",""],
["./messen.htm","Measure","Measure During surgeries new points are marked off from so-called points of reference with a pair of compasses for the orientation on the globe. N...",""],
["./methoden_zur_motilitaetsdiagno.htm","Methods for Motility Diagnosis","Methods for Motility Diagnosis In SEE++ there exist two possibilities for the interactive motility diagnosis: 1. Interpolation for Real-Time Asses...",""],
["./modelle.htm","Models","Models The toolbar for models consists of only one element to switch between the different simulation models . Left-click on the button to open th...",""],
["./motorische_fusionsbreite.htm","Motor Fusional Ability","Motor Fusional Ability This dialog provides the possibility to change the motor fusional ability of the \"virtual patient\". The motor fusional abil...",""],
["./muskeldaten.htm","Muscle Data","Muscle Data The muscle data dialog is one of the most central elements in the SEE++ system. It can be used to adjust the force model to pathologic...",""],
["./muskelwirkungsrichtung.htm","Muscle Force Vector","Muscle Force Vector Similar to the muscle force distribution diagram in the muscle force vector diagram the specific rotational components of the ...",""],
["./muskelwirkungsverteilung.htm","Muscle Force Distribution","Muscle Force Distribution The muscle force distribution diagram is a geometric diagram. You can find further information concerning the mathematic...",""],
["./neuerpatient.htm","New Patient/Patient Data","New Patient/Patient Data Each time you create a new patient, the patient data dialog is displayed. Otherwise you can open the dialog via the main ...",""],
["./neue_pathologie.htm","New Pathology","New Pathology With the help of this function you can generate a new pathology for the current patient. First choose the type of pathology you want...",""],
["./operationen.htm","Surgeries","Surgeries SEE++ interactively simulates the most popular surgery techniques. If you want to simulate a surgery with the system, a surgery step alw...",""],
["./optionen.htm","Options","Options SEE++ provides general options, which allow specific default settings to make it easier to work with the system. Each time SEE++ is quit, ...",""],
["./orbit_datenimportieren.htm","Import Orbit-Files","Import Orbit-Files With this function you can import a complete patient file from the Orbit&#8482; program into a scenario of SEE++. After selecting the...",""],
["./overview.htm","Overview","Overview A first \"attempt\" for the development of a mathematical model of the human eye was formulated by Krewson in 1950. This model defined excl...",""],
["./patientenverwaltung.htm","Patient Management","Patient Management The patient management can be accessed via the \"Patient\" item of the main menu. In SEE++ a patient is saved as a dataset consis...",""],
["./patientladen.htm","Open Patient","Open Patient With the function \"Open Patient\" an already saved patient is loaded into the program. Navigate to the directory you saved your patien...",""],
["./patientspeichern.htm","Save Patient","Save Patient This menu item is used to save the current patient data as a file on your data storage volume. Navigate to the directory you want to ...",""],
["./pulleymodell.htm","Pulley Models","Pulley Models The SEE++ system implements 3 models that consider pulleys, namely the SEE-KID model, the SEE-KID active pulley model and the Orbit ...",""],
["./referenzdaten.htm","Reference Data","Reference Data The SEE++ simulation model simulates the oculomotoric system via a biomechanical model consisting of two eyes and a \"virtual\" refer...",""],
["./referenzdatenexportieren.htm","Export","Export The export of reference data allows you to save the whole parameter set of an eye into a reference data file. Via the menu item \"Reference ...",""],
["./referenzdatenimportieren.htm","Import","Import The import of reference data loads a saved reference data file into a selected eye. Thereby the eye where the reference data is loaded to i...",""],
["./schielen.htm","Strabismus","Strabismus Every permanent or regularly occurring misalignment of the eyes is described as squinting (\"Strabismus\"). Thereby the eyes are not para...",""],
["./schielwinkeldiagramm.htm","Squint-Angles Diagram","Squint-Angles Diagram In principle the squint-angles diagram is simply a different display format for the Hess-diagram. However, in the squint-ang...",""],
["./seeppreferenz.htm","SEE++ Reference","SEE++ Reference This part of the manual describes all functions provided by SEE++. You can access this help reference anytime from within the prog...",""],
["./seeppverwenden.htm","Using SEE++","Using SEE++ SEE++ is used in the following task flow: 1. Parameterization with Patient Data The goal of SEE++ is to offer an as realistic as possi...",""],
["./seitenansicht.htm","Print Preview","Print Preview You can access the print preview of a diagram via its context menu and of the 3D-view via the main menu under \"Patient- 3D-Model- Pr...",""],
["./simulation.htm","Simulation","Simulation SEE++ uses a biomechanical model for simulating the binocular Hess-Lancaster test. The results of this test can be visualized in form o...",""],
["./stateviewer.htm","Stateviewer","Stateviewer The Stateviewer can be displayed for all three eyes (left eye, right eye, reference eye) and is rather addressed to experienced users,...",""],
["./supranukleaererectusmedialis.htm","Supranuclear Gaze Palsy","Supranuclear Gaze Palsy The third example describes a dexter supranuclear gaze palsy. The lesion for this simulation should be cortical (cerebral ...",""],
["./symbolleisten.htm","Toolbars","Toolbars The SEE++ system provides toolbars for using the most important functions of the program fast and easy. There exist four different toolba...",""],
["./symbolleistenansichten.htm","Views","Views The views toolbar is used to administrate different views. A view is the sum of all settings, which can be made for the diagrams and the 3D-...",""],
["./systemvoraussetzungen.htm","System Requirements","System Requirements SEE++ runs on computers with a Windows&#174; operating system installed. Due to the graphically extensive representation and the co...",""],
["./szenarien.htm","Scenarios","Scenarios Scenarios can be edited exclusively via the Treeview. In a scenario all three eyes (reference eye, left eye, right eye) with all the cor...",""],
["./szenarienansichten.htm","Views","Views You can assign a view to each scenario. To do so, use the menu item \"Assign Current View to Scenario\". A view is the sum of all properties y...",""],
["./tangentialeverlagerung.htm","Tangential Transposition","Tangential Transposition The tangential transposition works similar to the transposition or the anterior/posterior transposition. To do so, select...",""],
["./textuell.htm","Non-Graphical","Non-Graphical The transposition of an insertion can also be carried out in a non-graphical way. To do so, open the dialog for the non-graphical tr...",""],
["./titel.htm","SEE++","SEE++ Benutzerhandbuch Revision 11 www.strabismus.at Michael.Buchberger@gmx.at s.priglinger@outlook.com SEE++ is the software implementation of th...",""],
["./triangulation.htm","Triangulation","Triangulation The triangulation is based on the measurement function, whereas here the marking off with a pair of compasses is supported. To acces...",""],
["./trochlearisparese.htm","Superior Oblique Palsy","Superior Oblique Palsy In the second example, a superior oblique palsy of the right eye is simulated. This palsy is, similar to the abducens palsy...",""],
["./ueberblick.htm","Overview","Overview After starting SEE++ the following view of the main window is displayed: When the program is launched for the first time this default vie...",""],
["./versetzen.htm","Transposition","Transposition The transposition of an insertion can be performed in an interactive or in a non-graphical way. If you want to transpose an insertio...",""],
["./vorruecklagern.htm","Anterior/Posterior Transposition","Anterior/Posterior Transposition The surgery technique anterior/posterior transposition relocates an insertion point along its muscle action circl...",""],
["./vorwort.htm","Preface","Preface Increasing automation within all areas in everyday life make the application of software systems for administration and services essential...",""],
["./wasistseepp.htm","What is SEE++","What is SEE++ SEE++ is a new simulation system for the prediction of clinical surgery results as well as for the illustration of pathological situ...",""]];
