pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./abducensparese.htm","Abduzensparese","Abduzensparese Für das erste Beispiel soll eine Abduzensparese am rechten Auge simuliert werden. Die Abduzensparese ist eine inkomitante Schielfor...",""],
["./aenderungsbericht.htm","Änderungsbericht","Änderungsbericht Der Änderungsbericht bietet die Möglichkeit, eine textuelle Aufstellung aller Änderungen zwischen jeweils zwei Szenarien vom gewä...",""],
["./allgemeinefunktionen.htm","Allgemeine Funktionen","Allgemeine Funktionen Die Symbolleiste für \"Allgemeine Funktionen\" stellt die wichtigsten Navigations- und Darstellungsfunktionen zur Verfügung. V...",""],
["./allgemeines.htm","Allgemeines","Allgemeines Die Allgemeinen Optionen von SEE++ sind in einem Dialog einstellbar, den sie in der Treeview unter \"Optionen- Allgemein\" oder im Haupt...",""],
["./ansichten.htm","Ansichten","Ansichten Wie bereits in der Einleitung erklärt, bietet SEE++ vier so genannte Diagramm-Fenster um verschiedene Diagramme darzustellen. In jedes d...",""],
["./avi_filmerstellen.htm","AVI-Film erstellen","AVI-Film erstellen Eine weitere Option, um Daten aus SEE++ zu exportieren, ist die Funktion, aktuelle Simulationsergebnisse zur besseren Darstellu...",""],
["./baendermodell.htm","Bändermodell","Bändermodell Basierend auf dem Fadenmodell formulierte Robinson 1975 das so genannte Bändermodell. Dieses Modell reduziert die Verschiebung des Mu...",""],
["./bericht.htm","Bericht","Bericht Der Bericht liefert eine komplette Auflistung aller Parameter des aktuell aktiven Simulationsmodells und den entsprechenden Werten. Wählen...",""],
["./bilderspeichern.htm","Bilder speichern","Bilder speichern Wählen sie \"Bild speichern\" aus dem Kontextmenü eines Diagramms bzw. für die 3D-Ansicht aus dem Hauptmenü \"Patient- 3D-Modell- Al...",""],
["./blickschema.htm","Blickschema","Blickschema Ein Blickschema bildet die Basis für die Simulation des Hess-Lancaster Tests. Bei der Durchführung der Simulation wird für jeden im Bl...",""],
["./blickschema_als_bild_speichern.htm","Blickschema als Bild speichern","Blickschema als Bild speichern Über diesen Dialog können sie die neun Hauptblickrichtungen (Standard-Blickschema), dargestellt in der 3D-Ansicht ,...",""],
["./bulbusdaten.htm","Bulbusdaten","Bulbusdaten Der Bulbusdaten-Dialog existiert für jedes der von SEE++ simulierten Augen . In dieser Erklärung wird das linke Auge als Beispiel verw...",""],
["./cover_test.htm","Cover Test","Cover Test Die Simulation des Cover Tests baut auf der \"Interpolation für Echtzeit-Diagnose\" auf, das heißt für die Verwendung des Cover Tests mus...",""],
["./cover_test_med_hintergrund.htm","Cover Test","Cover Test Der Cover Test oder Abdecktest wird zur objektiven Bestimmung der Art und des Ausmaßes einer Augenmuskelstörung durch Fixierenlassen ei...",""],
["./datenexport.htm","Datenexport","Datenexport Unter Funktionen für Datenexport wird in SEE++ das Speichern von Bildern, Videos bzw. das Ausdrucken von Diagrammen und Ansichten vers...",""],
["./diagramme.htm","Diagramme","Diagramme Die Optionen für Diagramme beziehen sich auf die Darstellung der einzelnen verfügbaren Ansichten in SEE++. In diesem Dialog gibt es für ...",""],
["./diagrammeallgemein.htm","Diagramme","Diagramme Die acht Diagramme in SEE++ haben gewisse Gemeinsamkeiten. Eine Gemeinsamkeit ist, dass pro Diagramm-Fenster immer nur ein Diagramm ange...",""],
["./drucken.htm","Drucken","Drucken Das Drucken eines Diagramms oder der 3D-Ansicht kann über das Kontextmenü eines Diagramms bzw. für die 3D-Ansicht, im Hauptmenü unter \"Pat...",""],
["./drucker.htm","Drucker","Drucker Mit dem Optionsdialog \"Drucker\" können sie die Einstellungen des von SEE++ standardmäßig verwendeten Druckers festlegen. Öffnen sie diesen...",""],
["./einfuehrendebeispiele.htm","Einführende Beispiele","Einführende Beispiele Dieser Abschnitt umfasst drei verschiedene Beispiele, die mit Hilfe von SEE++ modelliert wurden: 1. Abduzensparese - als Bei...",""],
["./fadenmodell.htm","Fadenmodell","Fadenmodell Das Fadenmodell ist die einfachste Repräsentation, um die geometrische Wirkung der Augenmuskulatur zu beschreiben. Es wurde von Krewso...",""],
["./film_fuer_kopfneigetest.htm","Film für Kopfneigetest","Film für Kopfneigetest Die Funktion \"Film für Kopfneigetest\" ermöglicht es, AVI-Filme in einer bestimmten Blickposition mit wechselnder Kopfneigun...",""],
["./geometrischemodelle.htm","Geometrische Modelle","Geometrische Modelle SEE++ implementiert sowohl die rein geometrischen Modelle (Faden- und Bändermodell) als auch die kinematischen Modelle mit ge...",""],
["./grundlagenderanatomie.htm","Grundlagen der Anatomie","Grundlagen der Anatomie Die Augen, der \"Gesichtssinn\", zählen zu den wichtigsten Sinnesorganen des menschlichen Organismus. Sie liefern uns ein st...",""],
["./hess_diagramm.htm","Hess-Diagramm","Hess-Diagramm Im Programm SEE++ gibt es zwei Hess-Diagramme: eines für das linke Auge bei Rechts-Fixation und eines für das rechte Auge bei Links-...",""],
["./hess_lancastertest.htm","Hess-Lancaster Test","Hess-Lancaster Test Der Hess-Lancaster Test oder Hess-Test ist ein Test für Binokularfunktionen mit für beide Augen getrennten Bildern. Dieser kli...",""],
["./innervationsverteilung.htm","Innervationsverteilung","Innervationsverteilung Der Dialog der Innervationsverteilung steuert das Aktivierungspotential der Muskeln auf Basis der von den motorischen Kerne...",""],
["./interpolation_fuer_echtzeit_di.htm","Interpolation für Echtzeit-Diagnose","Interpolation für Echtzeit-Diagnose Die Interpolation für Echtzeit-Diagnose kann über die Symbolleiste für \"Allgemeine Funktionen\" aufgerufen werd...",""],
["./kinematischemodelle.htm","Kinematisches Modell","Kinematisches Modell Um ein mechanisches System vollständig simulieren zu können, wird neben geometrischen Strukturen auch die Simulation von Kräf...",""],
["./klinischereinsatz.htm","Klinischer Einsatz","Klinischer Einsatz Da dieses System primär als Forschungsunterstützung angesehen werden muss, ergeben sich wichtige Einschränkungen für den klinis...",""],
["./kraeftemodell.htm","Kräftemodell","Kräftemodell Ziel des Kräftemodells ist es, das Verhalten eines Muskels in Abhängigkeit von seiner Länge und Innervation zu simulieren. Dies wird ...",""],
["./medizinischestammdaten.htm","Medizinische Stammdaten","Medizinische Stammdaten Die medizinischen Stammdaten umfassen sämtliche Daten, die für eine Modellierung und Simulation eines \"virtuellen Patiente...",""],
["./messen.htm","Messen","Messen Für die Orientierung am Bulbus werden bei Operationen von so genannten Orientierungs- oder Messpunkten aus mit einem Zirkel neue Punkte abg...",""],
["./methoden_zur_motilitaetsdiagno.htm","Methoden zur Motilitätsdiagnose","Methoden zur Motilitätsdiagnose In SEE++ gibt es zwei Möglichkeiten zur interaktiven Motilitätsdiagnose: 1. Interpolation für Echtzeit-Diagnose 2....",""],
["./modelle.htm","Modelle","Modelle Die Symbolleiste für Modelle besteht ausschließlich aus einem Element zum Umschalten der verschiedenen Simulationsmodelle . Klicken sie mi...",""],
["./motorische_fusionsbreite.htm","Motorische Fusionsbreite","Motorische Fusionsbreite In diesem Dialog kann die motorische Fusionsbreite des \"virtuellen Patienten\" verändert werden. Die Fusionsbreite kann en...",""],
["./muskeldaten.htm","Muskeldaten","Muskeldaten Der Muskeldaten-Dialog ist eines der zentralsten Elemente des SEE++ Systems. Hier kann das Kräftemodell pathologischen Gegebenheiten h...",""],
["./muskelwirkungsrichtung.htm","Muskelwirkungsrichtung","Muskelwirkungsrichtung Ähnlich wie beim Muskelwirkungsverteilungsdiagramm werden im Muskelwirkungsrichtungsdiagramm die einzelnen Rotationskompone...",""],
["./muskelwirkungsverteilung.htm","Muskelwirkungsverteilung","Muskelwirkungsverteilung Das Muskelwirkungsverteilungsdiagramm ist ein geometrisches Diagramm. Genauere Informationen über die mathematischen Hint...",""],
["./neuerpatient.htm","Neuer Patient/Patientenstammdaten","Neuer Patient/Patientenstammdaten Den Dialog für die Patientenstammdaten sehen sie immer, wenn sie einen neuen Patienten anlegen. Ansonsten erreic...",""],
["./neue_pathologie.htm","Neue Pathologie","Neue Pathologie Mit dieser Funktion können sie eine neue Pathologie für den aktuellen Patienten generieren. Wählen sie als erstes die Art von Path...",""],
["./operationen.htm","Operationen","Operationen SEE++ bildet die gängisten Operationstechniken interaktiv nach. Will man mit dem System eine Operation nachbilden, so besteht ein Oper...",""],
["./optionen.htm","Optionen","Optionen SEE++ stellt allgemeine Optionen zur Verfügung, die es ermöglichen bestimmte Standardeinstellungen vorzunehmen, um das Arbeiten mit dem S...",""],
["./orbit_datenimportieren.htm","Orbit-Daten importieren","Orbit-Daten importieren Mit dieser Funktion kann eine komplette Patientendatei des Programms Orbit&#8482; in ein Szenario von SEE++ importiert werden. N...",""],
["./overview.htm","Überblick","Überblick Ein erster \"Versuch\" für die Entwicklung eines mathematischen Modells des menschlichen Auges wurde von Krewson 1950 formuliert. Dieses M...",""],
["./patientenverwaltung.htm","Patientenverwaltung","Patientenverwaltung Die Patientenverwaltung kann im Hauptmenü über den Menüpunkt \"Patient\" verwendet werden. In SEE++ wird als Patient ein gesamte...",""],
["./patientladen.htm","Patient laden","Patient laden Mit der Funktion \"Patient laden\" wird ein bereits gespeicherter Patient wieder in das Programm geladen. Navigieren sie in das Verzei...",""],
["./patientspeichern.htm","Patient speichern","Patient speichern Diese Menüfunktion wird verwendet, um die aktuellen Patientendaten als Datei zu speichern. Navigieren sie in das Verzeichnis, in...",""],
["./pulleymodell.htm","Pulleymodelle","Pulleymodelle Das SEE++ System implementiert 3 Modelle, die Pulleys berücksichtigen, nämlich das SEE-KID Modell, das SEE-KID Active Pulley Modell ...",""],
["./referenzdaten.htm","Referenzdaten","Referenzdaten Das SEE++ Simulationsmodell bildet das okulomotorische System mit Hilfe eines biomechanischen Modells bestehend aus zwei Augen und e...",""],
["./referenzdatenexportieren.htm","Exportieren","Exportieren Das Exportieren von Referenzdaten ermöglicht das Speichern der gesamten Simulationsdaten eines Auges in eine Referenzdaten Datei. Wähl...",""],
["./referenzdatenimportieren.htm","Importieren","Importieren Das Importieren von Referenzdaten lädt eine gespeicherte Referenzdaten-Datei wieder in ein gewähltes Auge. Dabei ist das Auge, in das ...",""],
["./schielen.htm","Schielen","Schielen Als Schielen (\"Strabismus\") bezeichnet man jede beständige oder nur hin und wieder auftretende Fehlstellung der Augen. Dabei stehen die A...",""],
["./schielwinkeldiagramm.htm","Schielwinkeldiagramm","Schielwinkeldiagramm Das Schielwinkeldiagramm ist im Prinzip nur eine andere Darstellungsform für das Hess-Diagramm. Allerdings werden im Schielwi...",""],
["./seeppreferenz.htm","SEE++ Referenz","SEE++ Referenz Dieser Teil des Handbuchs beschreibt alle in SEE++ verfügbaren Funktionen. Innerhalb des Programmes können sie diese Hilfe jederzei...",""],
["./seeppverwenden.htm","SEE++ verwenden...","SEE++ verwenden... SEE++ wird in einem durchgängigen Prozess verwendet: 1. Parametrierung mit Patientendaten Ziel von SEE++ ist es, eine möglichst...",""],
["./seitenansicht.htm","Seitenansicht","Seitenansicht Die Seitenansicht für das Drucken eines Diagramms oder der 3D-Ansicht wird im Kontextmenü der Diagramme bzw. für die 3D-Ansicht im H...",""],
["./simulation.htm","Simulation","Simulation SEE++ simuliert mit Hilfe des biomechanischen Modells den binokularen Hess-Lancaster Test. Die Ergebnisse des Tests können in Form von ...",""],
["./stateviewer.htm","Stateviewer","Stateviewer Der Stateviewer kann für alle drei Augen (linkes Auge, rechtes Auge, Referenzauge) angezeigt werden und richtet sich eher an erfahrene...",""],
["./supranukleaererectusmedialis.htm","Supranukleäre Augenbewegungsstörung","Supranukleäre Augenbewegungsstörung Das dritte Beispiel beschreibt eine rechtsseitige Blicklähmung. Die Schädigung soll kortikal an der Großhirnri...",""],
["./symbolleisten.htm","Symbolleisten","Symbolleisten Das SEE++ System stellt Symbolleisten zur Verfügung, um die wichtigsten Funktionen im Programm schnell und einfach bedienen zu könne...",""],
["./symbolleistenansichten.htm","Ansichten","Ansichten Die Symbolleiste für Ansichten dient zum Verwalten von verschiedenen Ansichten, wobei eine Ansicht die Summe aller Einstellungen ist, di...",""],
["./systemvoraussetzungen.htm","Systemvoraussetzungen","Systemvoraussetzungen SEE++ läuft grundsätzlich auf Rechnern mit Windows&#174; Betriebssystemen. Aufgrund der grafisch aufwändigen Darstellung und der ...",""],
["./szenarien.htm","Szenarien","Szenarien Szenarien können ausschließlich über die Treeview bearbeitet werden. In einem Szenario werden alle drei Augen (Referenzauge, linkes Auge...",""],
["./szenarienansichten.htm","Ansichten","Ansichten Sie können jedem Szenario eine Ansicht zuordnen. Verwenden sie dazu den Menüpunkt \"Aktuelle Ansicht dem Szenario zuordnen\". Eine Ansicht...",""],
["./tangentialeverlagerung.htm","Tangentiale Verlagerung","Tangentiale Verlagerung Die tangentiale Verlagerung funktioniert ähnlich wie die Versetzung bzw. Vor/Rücklagerung. Wählen sie dazu in der Treeview...",""],
["./textuell.htm","Textuell","Textuell Die Versetzung eines Insertionspunktes kann auch textuell durchgeführt werden. Öffnen sie hierzu den Dialog zum textuellen Versetzen im H...",""],
["./titel.htm","SEE++","SEE++ Benutzerhandbuch Revision 11 http://www.strabismus.at Michael.Buchberger@gmx.at s.priglinger@outlook.com SEE++ ist die software technische U...",""],
["./triangulation.htm","Triangulation","Triangulation Die Triangulation basiert auf der Funktion des Messens , wobei hier das Abschlagen mit einem Zirkel unterstützt wird. Um diese Funkt...",""],
["./trochlearisparese.htm","Trochlearisparese","Trochlearisparese Im zweiten Beispiel soll eine m. obliquus superior Parese am rechten Auge simuliert werden. Auch dies ist ebenso wie die Abduzen...",""],
["./ueberblick.htm","Überblick","Überblick Wenn SEE++ gestartet wird, erscheint folgende Ansicht des Hauptfensters: Beim ersten Start des Programmes wird diese Standardansicht ang...",""],
["./versetzen.htm","Versetzen","Versetzen Das Versetzen einer Insertion kann interaktiv oder textuell durchgeführt werden. Wenn sie mit der Maus eine Insertion versetzen möchten,...",""],
["./vorruecklagern.htm","Vor/Rücklagern","Vor/Rücklagern Die Operationstechnik des Vor/Rücklagerns versetzt einen Insertionspunkt entlang seines Muskelwirkungskreises. Wenn sich das Auge n...",""],
["./vorwort.htm","Vorwort","Vorwort Zunehmende Automatisierung in allen Bereichen unseres Alltages macht den Einsatz von Softwaresystemen für Verwaltung und Dienstleistungen ...",""],
["./wasistseepp.htm","Was ist SEE++","Was ist SEE++ SEE++ ist ein neuartiges Simulationssystem zur Vorhersage von klinischen Operationsergebnissen, sowie zur Darstellung von pathologis...",""]];
