name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
          token: ${{ github.token }}
          tag: v11.0
          assets: |
            changelog.txt
            *.zip
    - name: Upload SEEPP_Setup_Win32.exe
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/SEEPP_Setup_Win32.exe
          asset_name: SEEPP_Setup_Win32.exe
          tag: ${{ github.ref }}
          overwrite: true
    - name: Upload SEEPP_Setup_x64.exe
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release/SEEPP_Setup_x64.exe
          asset_name: SEEPP_Setup_x64.exe
          tag: ${{ github.ref }}
          overwrite: true
